### ISSUE TITLE
Hot get the user name from his UUID?

### ISSUE THREAD

**Issue by luxio** [signalpoint/webform#13]
The webform_service module delivers the UUID of the user of a submission. How do I retrieve the user name from his UUID?

**Comment by signalpoint** [comment]
@luxio As someone who took over the webform_service module for Drupal, the uuid dependency on the module drives me crazy. I really do hate it because of the added complexity for the uuids. At this point I'm not aware of a way to get the uid/name from a submission. You could use a custom module in Drupal to post process the service resource results to load/append this extra data to the submission: http://cgit.drupalcode.org/services/tree/docs/services.alter.api.php?h=7.x-3.x

**Comment by luxio** [comment]
Thanks.
